export const singleAgentPayrollData = {
    agentId: 1,
    agentName: "wilson Mark - 2",
    payrollDetail: {
        "2021-03-16": {
            Regular: "6",
            D1: "2",
            D2: "",
            D3: "",
            PTOs: "",
            Bereaved: "",
            Overtime: "",
            HOL: "",
            EPL: "",
            EPFL: "",
            TotalHours: "8",
        },
        "2021-03-15": {
            Regular: "6",
            D1: "",
            D2: "",
            TotalHours: "6",
        },
        "2021-03-14": {
            Regular: "6",
            D1: "",
            TotalHours: "6",
        },
        "2021-03-13": {
            Regular: "6",
            D1: "1",
            D2: "",
            D3: "",
            PTOs: "2",
            Bereaved: "",
            Overtime: "",
            HOL: "",
            EPL: "",
            EPFL: "",
            TotalHours: "9",
        },
        "2021-03-12": {
            Regular: "6",
            D1: "1",
            D2: "",
            D3: "",
            PTOs: "",
            Bereaved: "",
            Overtime: "",
            HOL: "",
            EPL: "",
            EPFL: "",
            TotalHours: "7",
        },
        "2021-03-11": {
            Regular: "6",
            D1: "",
            D2: "",
            D3: "2",
            PTOs: "",
            Bereaved: "",
            Overtime: "",
            HOL: "",
            EPL: "",
            EPFL: "",
            TotalHours: "8",
        },
        "2021-03-10": {
            Regular: "6",
            D1: "",
            D2: "",
            D3: "",
            PTOs: "",
            Bereaved: "2",
            Overtime: "2",
            HOL: "",
            EPL: "",
            EPFL: "",
            TotalHours: "10",
        },
    
    }
}