export const agentsData = [
    {
        "id": 1,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Jaylon Rhiel Madsen",
        "ticket_number": 77,
        "dispute_type": "Day",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "hour": "5",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Pending",
        "action": false,
        "reason": "sick",
        "agents": {
            "id": 1,
            "dispute_type": true,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "hours": "4",
            "supervisor_hours": "4:52",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Pending"
        }
    },
    {
        "id": 2,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Llewellyn",
        "ticket_number": 77,
        "dispute_type": "Week",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "hour": "5",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Approved",
        "action": false,
        "reason": "Vacations",
        "agents": {
            "id": 2,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "hours": "4",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "supervisor_hours": "4:52",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Approved"
        }
    },
    {
        "id": 3,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Llewellyn",
        "ticket_number": 77,
        "dispute_type": "Pay Period",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Reject",
        "action": false,
        "reason": "Vacations",
        "hour": "5",
        "agents": {
            "id": 3,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "hours": "4",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "supervisor_hours": "4:52",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Reject"
        }
    },
    {
        "id": 4,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Llewellyn",
        "ticket_number": 77,
        "dispute_type": "Day",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "hour": "5",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Partial-Approved",
        "action": false,
        "reason": "Vacations",
        "agents": {
            "id": 4,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "hours": "4",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "supervisor_hours": "4:52",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Partial-Approved"
        }
    },
    {
        "id": 5,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Llewellyn",
        "ticket_number": 77,
        "dispute_type": "Week",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "hour": "5",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Approved",
        "action": false,
        "reason": "Vacations",
        "agents": {
            "id": 5,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "hours": "4",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "supervisor_hours": "4:52",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Approved"
        }
    },
    {
        "id": 6,
        "image": "https://robohash.org/providentametvoluptates.png?size=50x50&set=set1",
        "agent_name": "Llewellyn",
        "ticket_number": 77,
        "dispute_type": "Pay Period",
        "start_date": "1/20/2022",
        "stop_date": "2/12/2022",
        "hour": "5",
        "comments": "Repair Right Ankle Joint, Open Approach",
        "status": "Partial-Approved",
        "action": false,
        "reason": "Vacations",
        "agents": {
            "id": 6,
            "start_date": "1/20/2022",
            "stop_date": "2/12/2022",
            "hours": "4",
            "agent_note": "Repair Right Ankle Joint, Open Approach",
            "supervisor_start_date": "1/20/2022",
            "supervisor_stop_date": "2/12/2022",
            "supervisor_hours": "4:52",
            "supervisor_note": "Repair Right Ankle Joint, Open Approach",
            "status": "Partial-Approved"
        }
    }
]